name: Path based filtering

on:
  push:
    branches:
      - master
    paths:
    - "path/**"

jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List Repo
      run: ls