name: List Repo Manually

on:
  workflow_dispatch:

jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List Repo
      run: |
        cd path

    - name: List Repo
      run: ls