name: Generate Vars

on:
  push:
    branches:
      - master

jobs:
  list-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List Repo
      run: ls
    
    - name: Generate Vars
      id: generate_vars
      run: |
        # Just Tag
        IMAGE_TAG=sha-$(echo $(git rev-parse --short HEAD) | cut -c1-7)
        # Just Image name
        IMAGE_NAME=${{ github.repository }}-gh-sample
        #Image ID= Name + Tag
        IMAGE_ID=$IMAGE_NAME:$IMAGE_TAG
        IMAGE_REPO=$REGISTRY/$IMAGE_ID
        IMAGE=$(echo $IMAGE_REPO | tr '[:upper:]' '[:lower:]')
        echo "Image: $IMAGE"
        echo "::set-output name=image::$IMAGE"
        echo "::set-output name=image_name::$IMAGE_NAME"
        echo "::set-output name=image_tag::$IMAGE_TAG"

    - name: Output Vars
      run: |
        echo ${{ steps.generate_vars.outputs.image }}
